language: python

python:
    - "2.7"
    # - "3.4"

cache:
    directories:
        - $HOME/.cache

sudo: false

compiler:
    - gcc

before_install:
    - GIRDER_VERSION=master
    - LARGE_IMAGE_VERSION=girder-2
    - main_path=$PWD
    - build_path=$PWD/build
    - mkdir -p $build_path

    - girder_path=$build_path/girder
    - rm -fr $girder_path
    - git clone https://github.com/girder/girder.git $girder_path && git -C $girder_path checkout $GIRDER_VERSION
    - ln -sf $main_path $girder_path/plugins/
    - ls -l $girder_path/plugins

    - large_image_path=$girder_path/plugins/large_image
    - git clone https://github.com/DigitalSlideArchive/large_image.git $large_image_path && git -C $large_image_path checkout $LARGE_IMAGE_VERSION

    # From python core, not sure if strictly necessary.
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then export PY3="true"; else export PY2="true"; fi

    - export MONGO_VERSION=3.2.8
    - export PY_COVG="ON"
    - CACHE=$HOME/.cache source $girder_path/scripts/install_mongo.sh
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version

    - CACHE=$HOME/.cache CMAKE_VERSION=3.1.0 CMAKE_SHORT_VERSION=3.1 source $girder_path/scripts/install_cmake.sh
    - cmake --version

    - mkdir -p $HOME/.cache/node_modules || true
    - ln -sf $HOME/.cache/node_modules .
    - nvm install v5
    - npm install -g npm
    - npm --version
    # - npm prune

    - pip install -U pip virtualenv

install:
    - cd $girder_path
    - pip install -r requirements-dev.txt -r $main_path/requirements.txt -e .[plugins]
    - pip install -U -r $large_image_path/requirements.txt
    - npm prune
    - npm install
    - girder-install web --plugins=digital_slide_archive,large_image,worker,jobs --dev

script:
    - mkdir -p $build_path/girder_testing_build
    - cd $build_path/girder_testing_build
    - cmake -DRUN_CORE_TESTS:BOOL=OFF -DBUILD_JAVASCRIPT_TESTS:BOOL=OFF -DTEST_PLUGINS:STRING=digital_slide_archive -DPYTHON_COVERAGE:BOOL=${PY_COVG} -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} -DCOVERAGE_MINIMUM_PASS=13 -DJS_COVERAGE_MINIMUM_PASS=0 $girder_path
    - make

    - JASMINE_TIMEOUT=15000 ctest -VV
