---
- name: Ensure the girder group exists
  group:
    name: "{{ girder_exec_group }}"
    state: present
  become: true

- name: Ensure the girder user exists
  user:
    shell: /bin/bash
    name: "{{ girder_exec_user }}"
    groups: "{{ girder_exec_group }}"
    append: yes
  become: true

- name: Give ownership of root dir to appropriate user
  file:
    path: "{{ root_dir }}"
    owner: "{{ girder_exec_user }}"
    group: "{{ girder_exec_group }}"
    mode: 0775
    state: directory
    recurse: no
  become: true

- name: Install curl
  apt:
    name: curl
    state: present
    install_recommends: no
  become: true

- name: Install aptitude
  apt:
    name: aptitude
    state: present
    update_cache: yes
    install_recommends: no
  become: true
  when: (vagrant is defined) or (docker is defined)

- name: Upgrade system packages
  apt:
    upgrade: safe
    force: yes
    update_cache: yes
    install_recommends: no
  become: true
  when: (vagrant is defined) or (docker is defined)

- name: Install pycurl and apt-transport-https package in order to use the apt_repository module and install from https
  apt:
    name:
      - python-pycurl
      - apt-transport-https
    install_recommends: no
    state: present
  become: true

- name: Install mongo shell on vagrant
  apt:
    name:
      - mongodb-org-shell
    install_recommends: no
    state: present
  become: true
  when: vagrant is defined

- name: Start mongo service on vagrant
  service:
    name: mongod
    state: started
  become: true
  when: vagrant is defined

- name: Install packages needed for girder plugins
  apt:
    name:
      - libldap2-dev
      - libsasl2-dev
      - libfontconfig
    install_recommends: no
    state: present
  become: true

- name: Create a docker group
  group:
    gid: 998
    name: docker
    state: present
  become: true
  when: docker is defined

- name: Join the docker group
  user:
    name: ubuntu
    append: yes
    groups: docker
    state: present
  become: true
  when: docker is defined

- name: Set /opt to public
  file:
    path: /opt
    mode: '0777'
  become: true

- name: Add .vimrc to make developers happy
  template:
    src: .vimrc
    dest: /home/ubuntu/.vimrc
    mode: 0644
    owner: root
  become: true
  when: docker is defined

- name: Fetch python3-distutils on vagrant
  apt:
    name:
      - python3-distutils
    install_recommends: no
    state: present
  become: true

- name: Fetch pip on vagrant
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp
  when: vagrant is defined

- name: Install pip on vagrant
  shell: >-
    python3 /tmp/get-pip.py
    pip --upgrade pip
  when: vagrant is defined
  become: true
