---
- hosts: local
  roles:
    - role: common
      tags: common
      when:
        - docker is defined
        - docker != "provision"
    - role: worker
      tags: worker
      when:
        - docker is defined
        - docker == "girder_worker"
    - role: girder.girder
      version: master
      # This no longer works due to a change in the Girder ansible role
      # girder_development_mode: true
      girder_version: "latest"
      girder_web: false
      girder_daemonize: false
      become: true
      become_user: "{{ girder_exec_user }}"
      tags: girder
      when:
        - docker is defined
        - docker == "girder"

    - role: girder
      tags: girder
      when:
        - docker is defined
        - docker == "girder"

    - role: provision
      tags: provision
      when:
        - docker is defined
        - docker == "provision"
  vars:
    root_dir: /opt/digital_slide_archive
    girder_admin_user: admin
    girder_admin_email: girder.admin@kitware.com
    girder_admin_password: password
    girder_socket_port: 8080
    girder_socket_scheme: http
    girder_exec_user: ubuntu
    girder_exec_group: ubuntu
    girder_root: /opt/girder
    worker_exec_user: ubuntu
    worker_exec_group: ubuntu
    mongo_private_ip: mongodb
    girder_api_url: http://histomicstk:8080/api/v1
    mongo_girder_database: girder
    mq_private_ip: rmq
    memcached_url: memcached
    # I'd rather use python 3.7, but ansible does not work with it without more
    # fiddling
    ansible_python_interpreter: python3.6
