---
- hosts: all
  roles:
    - role: girder.mongodb
      version: master
    - common
    - mq
    - worker
    - role: girder.girder
      version: master
      # girder_development_mode: true
      girder_version: "latest"
      # Setting girder_web to true installs nodejs
      girder_web: true
      become: true
      become_user: "{{ girder_exec_user }}"
    - girder
    - provision
  vars:
    vagrant: true
    root_dir: /opt/digital_slide_archive
    girder_admin_user: admin
    girder_admin_email: girder.admin@kitware.com
    girder_admin_password: password
    girder_socket_port: 8080
    girder_socket_scheme: http
    girder_exec_user: vagrant
    girder_exec_group: vagrant
    girder_root: /opt/girder
    worker_exec_user: vagrant
    worker_exec_group: vagrant
    mongo_private_ip: 127.0.0.1
    mq_private_ip: localhost
    girder_api_url: http://localhost:8080/api/v1
    mongo_girder_database: girder
    memcached_url: 127.0.0.1
  post_tasks:
    - name: Ensure we can rebuild the girder web client
      shell: >-
        bash -lc "girder build >/tmp/test_build.txt 2>&1"
      become: true
      become_user: "{{ girder_exec_user }}"

    - name: Test HistomicsUI
      shell: >-
        bash -lc "tox -e py36,flake8,lintclient >/tmp/test_test.txt 2>&1"
      args:
        chdir: "/opt/HistomicsUI"
      become: true
      become_user: "{{ girder_exec_user }}"
